services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe
      - POSTGRES_DB=blog

  web:
    build: .
    container_name: web
    ports:
      - 8000:8000
    environment:
      - DJANGO_SECRET_KEY="django-insecure-(8e-o%!g_kc7leg-=)$d!b65g5+f)5z@6-hj1%qyp=&#x)6d=x"
      - DJANGO_DEBUG=1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwe
      - POSTGRES_DB=blog
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      postgres:
        condition: service_healthy
