# Generated by Django 4.0.4 on 2022-04-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('article_id', models.IntegerField(verbose_name='Идентификатор статьи')),
                ('parent_id', models.IntegerField(verbose_name='Идентификатор родительского комментария')),
                ('date', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
