# Generated by Django 4.0.4 on 2022-04-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.IntegerField(default=0, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
