# Generated by Django 4.0.4 on 2022-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.IntegerField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='definition',
            field=models.CharField(max_length=140, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Заголовок'),
        ),
    ]
