# Generated by Django 4.0.4 on 2022-04-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_date_alter_article_definition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.IntegerField(default=123, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='definition',
            field=models.CharField(default=123, max_length=140, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default=123, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default=123, max_length=50, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
